### ISSUE TITLE
Remove exception list, make exceptions optional

### ISSUE THREAD

**Issue by johnbeech** [bbc/apache2-license-checker#5]
With reference to the Licence Dependency Aggregator tool:
https://github.com/bbc/licence-dependency-aggregator

I spoke with @RichardTribe and we agreed that there are separate valid use cases for an external  analysis tool, and an integrated pipeline tool (this checker) that are strongly opinionated about correct and valid licenses to use with a project.

However, maintaining an exception list makes no sense - it should be down to the to the user of the library which exceptions they want to make, and not maintained as part of this tool.

**Comment by ChrisBAshton** [comment]
Hello 👋watching this repository with great interest (after a good chat with @davidbuckhurst), as we may seek to integrate into our article renderer: https://github.com/bbc/simorgh

We want to release under Apache2, though have some concerns there may be incompatible licenses deep down in our dependencies.

I've tried running `apache2-license-checker` locally and it's listed 19 packages that are 'problems' because their license is `undefined`. In these cases the license is usually named in the project README, albeit in a difficult-to-parse way.

Instinctively, I'd imagined that I could point this library to our own `exceptions.js` file, but it looks as though I'd currently have to open a PR into the library directly to add to your own exceptions.js list, which as you state here may not scale very well!

I'm happy to contribute some dev time in making a PR. What would be the best way forward from your perspective? e.g. taking a parameter `apache2-license-checker --exceptions=./exceptions.js`

**Comment by johnbeech** [comment]
Hey Chris,

Glad to see your interest in this project. I to am keen to build this tool into our pipeline for a new test tool. I'm just trying to track down the npm publish rights so that I can merge and push some updates. I think the next version is the one that should let people create their own exceptions. The "undefined" licence is a two character bug when printing out problems that's fixed on a separate branch. When it works correctly it lists out the problematic licenses. I'm keen to actively maintain this utility, so if you want to help with a pull request that supports an external exceptions for, please go right ahead and I'll help with testing and code reviews. It sounds be possible to npm install off a branch or tag in the mean time.

Best wishes,

**Comment by johnbeech** [comment]
Hi @ChrisBAshton - I've published a new version of this tool that supports a local exceptions file.

Either use:
`npm install @bbc/apache2-license-checker --save-dev`
or
`npm install bbc/apache2-license-checker --save-dev`

And see how that goes, and then if need be, create an `license-exceptions.json` as described in README.md - let me know if that works for you.

Closing this issue based on merging #9
